version: '3'
services:
#mssql docker
  eprodaja-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - estomatolognet2022

  estomatolog-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=estomatolog-sql,1435;Database=eStomatolog;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5192:5192
    networks:
      - estomatolognet2022
    links:
      - eprodaja-sql
    depends_on:
      - eprodaja-sql
      
networks:
  estomatolognet2022:
    driver: bridge      