version: '3'
services:
#mssql docker
  estomatolog-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - estomatolognet2022

  estomatolog-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=estomatolog-sql,1433;Database=IB180012;User=sa;Password=QWElkj132!;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7265:7265
    networks:
      - estomatolognet2022
    links:
      - estomatolog-sql
    depends_on:
      - estomatolog-sql
      
networks:
  estomatolognet2022:
    driver: bridge      