version: '3'
services:
  # mssql docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - estomatolognet2022

  estomatolog-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - estomatolognet2022

  mailing-service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.mailservice
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
      - OUTLOOK_MAIL=estomatolog@outlook.com
      - OUTLOOK_PASS=RazvojSoftvera2!
    depends_on:
      - rabbitmq
      - estomatolog-sql
      - estomatolog-api
    networks:
      - estomatolognet2022
    ports:
      - 7101:80

  estomatolog-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=estomatolog-sql,1433;Database=IB180012;User=sa;Password=QWElkj132!;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=mypass
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 7265:7265
    networks:
      - estomatolognet2022
    links:
      - estomatolog-sql
    depends_on:
      - estomatolog-sql

networks:
  estomatolognet2022:
    driver: bridge
